#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cssr[-1]
	add ucitrack cssr
	set ucitrack.@cssr[-1].init=cssr
	commit ucitrack
	delete firewall.cssr
	set firewall.cssr=include
	set firewall.cssr.type=script
	set firewall.cssr.path=/var/etc/cssr.include
	set firewall.cssr.reload=1
	commit firewall
EOF

/usr/share/cssr/gfw2ipset.sh
rm -f /tmp/luci-indexcache
exit 0
