# This is free software, licensed under the Apache License, Version 2.0 .
#  2021 by sirpdboy

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Network Shares - Samba 4 SMB/CIFS module
LUCI_DEPENDS:=+samba4-server
PKG_NAME:=luci-app-samba4
PKG_VERSION:=1
PKG_RELEASE:=9

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
