#!/bin/sh
[ -f /www/luci-static/chuqitopd/icons/ethernet.png ] && mv -f /www/luci-static/chuqitopd/icons/ethernet.png /www/luci-static/resources/icons/ethernet.png
[ -f /www/luci-static/chuqitopd/icons/ethernet_disabled.png ] && mv -f /www/luci-static/chuqitopd/icons/ethernet_disabled.png /www/luci-static/resources/icons/ethernet_disabled.png
[ -f /www/luci-static/chuqitopd/icons/port_down.png ] && mv -f /www/luci-static/chuqitopd/icons/port_down.png /www/luci-static/resources/icons/port_down.png
[ -f /www/luci-static/chuqitopd/icons/port_up.png ] && mv -f /www/luci-static/chuqitopd/icons/port_up.png /www/luci-static/resources/icons/port_up.png
sed -i ":a;$!N;s/tmpl.render.*sysauth_template.*return/local scope = { duser = default_user, fuser = user }\nlocal ok, res = luci.util.copcall\(luci.template.render_string, [[<% include\(\"themes\/\" .. theme .. \"\/sysauth\"\) %>]], scope\)\nif ok then\nreturn res\nend\nreturn luci.template.render\(\"sysauth\", scope\)/;ba" /usr/lib/lua/luci/dispatcher.lua
sed -i ":a;$!N;s/t.render.*sysauth_template.*return/local scope = { duser = h, fuser = a }\nlocal ok, res = luci.util.copcall\(luci.template.render_string, [[<% include\(\"themes\/\" .. theme .. \"\/sysauth\"\) %>]], scope\)\nif ok then\nreturn res\nend\nreturn luci.template.render\(\"sysauth\", scope\)/;ba" /usr/lib/lua/luci/dispatcher.lua
rm -Rf /var/luci-*cache*

uci batch <<-EOF
	set luci.themes.chuqitopd=/luci-static/chuqitopd
	set luci.main.mediaurlbase=/luci-static/chuqitopd
	commit luci
EOF
exit 0
