#!/bin/sh
[ -f /www/luci-static/chuqi/icons/ethernet.png ] && mv -f /www/luci-static/chuqi/icons/ethernet.png /www/luci-static/resources/icons/ethernet.png
[ -f /www/luci-static/chuqi/icons/ethernet_disabled.png ] && mv -f /www/luci-static/chuqi/icons/ethernet_disabled.png /www/luci-static/resources/icons/ethernet_disabled.png
[ -f /www/luci-static/chuqi/icons/port_down.png ] && mv -f /www/luci-static/chuqi/icons/port_down.png /www/luci-static/resources/icons/port_down.png
[ -f /www/luci-static/chuqi/icons/port_up.png ] && mv -f /www/luci-static/chuqi/icons/port_up.png /www/luci-static/resources/icons/port_up.png

rm -Rf /var/luci-*cache*

uci batch <<-EOF
	set luci.themes.CHUQi=/luci-static/chuqi
	set luci.main.mediaurlbase=/luci-static/chuqi
	commit luci
EOF
exit 0
