#!/bin/sh
n=zerotier
[ "$1" = up -a "$(uci -q get $n.@$n[0].nat)" = 1 -a "$2" ] || exit
X=iptables
let a=$(echo $2 | awk '{print NF-1}')+1
extract_rules(){
	echo "*$1"
	iptables-save -t $1 | grep $n | sed -e "s/^-A \(FORWARD\|POSTROUTING\)/-I \1 1/"
	echo 'COMMIT'
}

check(){
	r=1
	while [ $(ifconfig | grep -c zt) -lt $a ];do
		[ $r -gt 3 ] && return 1 || let r++
		sleep 1
	done
}
! check && [ $(ifconfig | grep -c zt) = 0 ] && exit

for i in $(ifconfig | grep 'zt' | awk '{print $1}');do
	$X -I FORWARD -i $i -m comment --comment $n -j ACCEPT
	$X -I FORWARD -o $i -m comment --comment $n -j ACCEPT
	$X -I INPUT -i $i -m comment --comment $n -j ACCEPT
	$X -t mangle -I POSTROUTING -o $i -m comment --comment $n -j MARK --set-mark 9
	$X -t mangle -I PREROUTING -i $i -m comment --comment $n -j MARK --set-mark 9
done
$X -t nat -I POSTROUTING -m mark --mark 9 -m comment --comment $n -j MASQUERADE

cat <<-EOF >> /var/etc/$n.include
	iptables-save -c | grep -v $n | iptables-restore -c
	iptables-restore -n <<-EOT
	$(extract_rules filter)
	$(extract_rules nat)
	$(extract_rules mangle)
	EOT
EOF
