#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#  2021 by sirpdboy

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Network Shares - Samba SMB/CIFS module
LUCI_DEPENDS:=+samba36-server
PKG_NAME:=luci-app-samba
PKG_VERSION:=1
PKG_RELEASE:=9

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
